### ISSUE TITLE
无法启动、无法构建

### ISSUE THREAD

**Issue by anmeng777** [Kun-GitHub/RuoYi-Go#2]
是不是当前这个版本无法使用？

**Comment by Kun-GitHub** [comment]
不会呀，我本地能启动也能构建，我找个时间开个新环境，拉下代码跑跑看。你那边报什么错？记得改“读取的配置文件名称”

**Comment by Kun-GitHub** [comment]
我本地能跑的配置没上传，有服务器跟数据库信息，所以你看下你那边是不是配置问题

**Comment by anmeng777** [comment]
> 不会呀，我本地能启动也能构建，我找个时间开个新环境，拉下代码跑跑看。你那边报什么错？记得改“读取的配置文件名称”

修改后可以运行了，项目很棒，谢谢

**Comment by Kun-GitHub** [comment]
谢谢认可哈，只是接口还没写完整的哦，你要快的话，需要自己补，发现有很多可以复用，后面可以写个代码生成器

**Comment by Kun-GitHub** [comment]
有没兴趣参与到这个开源项目来呀？

**Comment by anmeng777** [comment]
> 有没兴趣参与到这个开源项目来呀？

可以，我能做点儿什么？

**Comment by Kun-GitHub** [comment]
> > 有没兴趣参与到这个开源项目来呀？
> 
> 可以，我能做点儿什么？

就是目前项目功能还没全部开发好，一起参与了把他开发完成咯
